// <auto-generated />
using System;
using Encounters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedClinic.Migrations.PostgreSQL.Migrations.Encounters
{
    [DbContext(typeof(EncountersDbContext))]
    [Migration("20260707175227_InitialEncountersCreate")]
    partial class InitialEncountersCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("encounters")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("audit_entries", "encounters");
                });

            modelBuilder.Entity("Encounters.Domain.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PatientId");

                    b.ToTable("encounters", "encounters");
                });

            modelBuilder.Entity("Encounters.Domain.Encounter", b =>
                {
                    b.OwnsMany("Encounters.Domain.Diagnosis", "Diagnoses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<Guid>("EncounterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Icd10Code")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("EncounterId");

                            b1.ToTable("encounter_diagnoses", "encounters");

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");
                        });

                    b.OwnsOne("Encounters.Domain.VitalSigns", "Vitals", b1 =>
                        {
                            b1.Property<Guid>("EncounterId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DiastolicBp")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_diastolic_bp");

                            b1.Property<int?>("HeartRateBpm")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_heart_rate_bpm");

                            b1.Property<int?>("OxygenSaturationPercent")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_spo2_percent");

                            b1.Property<int?>("RespiratoryRatePerMin")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_respiratory_rate");

                            b1.Property<int?>("SystolicBp")
                                .HasColumnType("integer")
                                .HasColumnName("vitals_systolic_bp");

                            b1.Property<decimal?>("TemperatureCelsius")
                                .HasPrecision(4, 1)
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("vitals_temperature_celsius");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)")
                                .HasColumnName("vitals_weight_kg");

                            b1.HasKey("EncounterId");

                            b1.ToTable("encounters", "encounters");

                            b1.WithOwner()
                                .HasForeignKey("EncounterId");
                        });

                    b.Navigation("Diagnoses");

                    b.Navigation("Vitals");
                });
#pragma warning restore 612, 618
        }
    }
}
