<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>mediclinic-apphost</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedClinic.Api\MedClinic.Api.csproj" />
    <ProjectReference Include="..\MedClinic.DbMigrator\MedClinic.DbMigrator.csproj" />
    <ProjectReference Include="..\MedClinic.DemoSeeder\MedClinic.DemoSeeder.csproj" />
  </ItemGroup>

</Project>
