<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Core\Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
    <ProjectReference Include="..\Billing.Contracts\Billing.Contracts.csproj" />
    <ProjectReference Include="..\..\Encounters\Encounters.Contracts\Encounters.Contracts.csproj" />
    <ProjectReference Include="..\..\Prescriptions\Prescriptions.Contracts\Prescriptions.Contracts.csproj" />
  </ItemGroup>

</Project>
